version: "3"
services:
  migrations:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: migration
    command: sh -c "npm start"
    env_file: .env
  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    container_name: order
    ports:
      - 3001:3001
    env_file: .env
    restart: unless-stopped
  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    container_name: product
    ports:
      - 3002:3002
    env_file: .env
    restart: unless-stopped
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: user
    ports:
      - 3003:3003
    env_file: .env
    restart: unless-stopped
  shopping:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      USER_URL: users:3003
      ORDER_URL: orders:3001
      PRODUCT_URL: products:3002
      PORT: 80
    restart: unless-stopped
