apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: microservice
spec:
  selector:
    app: users
  type: ClusterIP
  ports:
    - name: users
      protocol: TCP
      port: 3003
      targetPort: users
