apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: microservice
spec:
  selector:
    app: orders
  type: ClusterIP
  ports:
    - name: orders
      protocol: TCP
      port: 3001
      targetPort: orders
