apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: microservice
spec:
  selector:
    app: products
  type: ClusterIP
  ports:
    - name: products
      protocol: TCP
      port: 3002
      targetPort: products
